language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  - pip install ansible-lint
  
script:
  - echo $VAULT > ~/.vault
  - ansible-playbook -i hosts site.yml --syntax-check
  - ansible-lint *.yml
